<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Admin-PC" ignored="1" name="Default test(failed)" tests="4" failures="1" timestamp="01 Mar 2019 07:38:40 GMT" time="0.0" errors="0">
  <testcase name="b1" time="0.0" classname="firstt.runningfailedtest">
    <skipped/>
  </testcase> <!-- b1 -->
  <testcase name="b1" time="0.0" classname="firstt.runningfailedtest">
    <skipped/>
  </testcase> <!-- b1 -->
  <testcase name="b1" time="0.0" classname="firstt.runningfailedtest">
    <skipped/>
  </testcase> <!-- b1 -->
  <testcase name="b1" time="0.0" classname="firstt.runningfailedtest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at firstt.runningfailedtest.b1(runningfailedtest.java:14)
at firstt.runningfailedautomatically.b1(runningfailedautomatically.java:21)
... Removed 47 stack frames]]>
    </failure>
  </testcase> <!-- b1 -->
  <testcase name="b2" time="0.0" classname="firstt.runningfailedtest">
    <ignored/>
  </testcase> <!-- b2 -->
</testsuite> <!-- Default test(failed) -->
